version: "3.9"

services:

  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fastify
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  fastify_api:
    build: .
    container_name: fastify_api
    restart: always
    ports:
      - "3001:3000"

    env_file:
      - .env

    depends_on:
      mysql_db:
        condition: service_healthy

volumes:
  mysql_data: